name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --hook-stage manual --all-files

  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    needs: [pre-commit]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.11"]
        runs-on: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poke-env
        run: cd poke-env && python -m pip install . && cd ..

      ## copied from poke-env's CI (thank you!) ##
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout PS
        uses: actions/checkout@v3
        with:
          repository: smogon/pokemon-showdown
          path: pokemon-showdown
          submodules: recursive

      - name: Get last showdown commit hash
        id: showdown-hash
        run: |
          cd pokemon-showdown/
          export hash=`git log -1 --pretty=format:%H`
          echo "hash=$hash" >> $GITHUB_OUTPUT

      - name: Restore server cache
        uses: actions/cache@v3
        with:
          path: pokemon-showdown/node_modules
          key:
            showdown-python${{ matrix.python-version }}-${{
            steps.showdown-hash.outputs.hash }}
          restore-keys: showdown-python${{ matrix.python-version }}-

      - name: Install PS dependencies & setup config
        run: |
          cd pokemon-showdown
          npm install
          cp config/config-example.js config/config.js
          sed  -i 's/backdoor = true/backdoor = false/g' config/config.js
          sed  -i 's/simulatorprocesses = 1/simulatorprocesses = 2/g' config/config.js
          sed  -i 's/.workers = 1 = 1/.workers = 2/g' config/config.js

      - name: Start PS
        run:
          cd pokemon-showdown;node pokemon-showdown start --no-security
          --max-old-space-size=3000 &

      - name: Wait for server to be up
        run: |
          until $(curl --output /dev/null --silent --head --fail http://localhost:8000); do
          sleep .01
          done
          sleep 1
      ## end of poke-env's CI copy ##
      - name: Install package
        run: python -m pip install .[test]

      - name: Test package
        run: >-
          python -m pytest -ra --cov --cov-report=xml --cov-report=term
          --durations=20

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.4

  dist:
    needs: [pre-commit]
    name: Distribution build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build sdist and wheel
        run: pipx run build

      - uses: actions/upload-artifact@v3
        with:
          path: dist

      - name: Check products
        run: pipx run twine check dist/*

  publish:
    needs: [dist]
    name: Publish to PyPI
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          # Remember to tell (test-)pypi about this repo before publishing
          # Remove this line to publish to PyPI
          repository-url: https://test.pypi.org/legacy/
